//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Trans30.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_TRN_INTERFACE               102
#define IDD_CARDPPL_FORM                105
#define IDR_CARDPPLVIEW_TMPL            106
#define IDD_TRN_EXCHANGE                106
#define IDR_MAINFRAME                   128
#define IDR_TEXTTYPE                    129
#define TAB_DSTTAB_CAPTION              130
#define TAB_SUBTAB_CAPTION              131
#define TAB_DSTCMD_CAPTION              132
#define TAB_SUBCMD_CAPTION              133
#define TAB_TRNOPT_CAPTION              134
#define IDS_LICENSE_FILE                135
#define IDS_VERSION_NUMBER              136
#define IDD_TRN_OPTIONS                 140
#define IDI_BCANCEL                     141
#define IDI_BHELP                       142
#define IDI_BNO                         143
#define IDI_BOK                         145
#define IDR_CHILDWND                    147
#define IDR_DATA                        153
#define IDI_CRDFILES                    156
#define IDI_CARDFILE                    157
#define IDB_SMALLPPL                    166
#define IDI_BINSERT                     170
#define IDI_BDELETE                     171
#define IDI_BEDIT                       172
#define IDI_BSAVE                       173
#define IDD_TRN_TABLEDEST               177
#define IDD_TRN_TABLECMD                179
#define IDD_TRN_GENERAL                 181
#define IDD_TRN_PARM                    184
#define IDI_BADD                        185
#define IDD_TRN_START                   186
#define IDD_PPL_CHOOSE                  187
#define IDD_MESSAGEDLG                  188
#define IDD_PROGRESSDLG                 189
#define IDI_TRANS                       194
#define IDI_CONVS                       196
#define IDD_TRN_PROCESS                 198
#define IDR_TRAY                        203
#define IDR_GLOBE_AVI                   204
#define IDR_BINARY                      205
#define IDP_TLOGO                       1001
#define IDC_DIRPPL_T                    1019
#define IDC_DIRLOG_T                    1020
#define IDC_FILELOG_T                   1021
#define IDC_DIRPPL                      1022
#define IDC_DIRLOG                      1023
#define IDC_FILELOG                     1024
#define IDC_AUTOEXC                     1026
#define IDC_PPLIMP                      1029
#define IDC_PPLEXP                      1030
#define IDC_PPLIMP_N                    1031
#define IDC_USEIMP                      1032
#define IDC_USEEXP                      1033
#define IDC_PPLEXP_N                    1034
#define IDC_LISTPPL                     1036
#define IDC_PPL_FILE                    1038
#define IDC_PPL_KIND                    1040
#define IDC_PPL_NAME                    1041
#define IDC_PPL_LIST                    1042
#define IDC_INSERT                      1045
#define IDC_DELETE                      1046
#define IDC_EDIT                        1047
#define IDC_OK                          1048
#define IDC_CANCEL                      1049
#define IDC_PPL_SRC_UID                 1050
#define IDC_PPL_DST_UID                 1051
#define IDC_SAVE                        1052
#define IDC_PPL_PARM                    1056
#define IDC_EDIT_PARM                   1057
#define IDC_EDIT_FILE                   1059
#define IDC_TRNNAME                     1061
#define IDC_SCHEMA                      1062
#define IDC_STRMSG                      1063
#define IDC_DST_PROCESS                 1071
#define IDC_TABLE_MAP                   1073
#define IDC_PPL_SRC_PWD                 1081
#define IDC_PPL_SRC                     1082
#define IDC_PPL_DST_PWD                 1083
#define IDC_PPL_DST                     1084
#define IDC_TAB_SQL                     1085
#define IDC_PARM_LIST                   1089
#define IDC_TABLE_CMD                   1094
#define IDC_ADD                         1097
#define IDC_SELECTALL                   1107
#define IDC_DESELECT                    1108
#define IDC_LIST_TRN                    1110
#define IDC_DST_TABLE                   1112
#define IDC_DST_CONDITION               1113
#define IDC_SUB_SQL                     1116
#define IDC_TEXT                        1117
#define IDC_BREAK                       1118
#define IDC_STATUS                      1120
#define IDC_PROGRESS                    1123
#define IDC_SUBTEXT                     1125
#define IDC_SHOWERR                     1126
#define IDC_LANGID                      1127
#define IDC_DEFTYPE                     1129
#define IDC_TRACEOPR                    1136
#define IDC_TRACECMD                    1137
#define IDC_TRACESEL                    1138
#define IDC_DEPART                      1140
#define IDC_DEPART_T                    1141
#define IDC_FILEIMP                     1142
#define IDC_FILEEXP                     1143
#define IDC_FILEIMP_T                   1144
#define IDC_FILEEXP_T                   1145
#define IDC_NAMEARC                     1146
#define IDC_NAMEARC_T                   1147
#define IDC_DIRPUT                      1152
#define IDC_DIRPUT_T                    1153
#define IDC_EXCTIME                     1155
#define IDC_INTTIME                     1156
#define IDC_EXCTIME_T                   1157
#define IDC_INTTIME_T                   1158
#define IDC_MINIMIZE                    1161
#define IDC_SYSTRAY                     1162
#define IDC_DIRGET_T                    1167
#define IDC_DIRGET                      1168
#define IDC_DELFILE                     1169
#define IDC_WRITEOPR                    1170
#define IDC_FILEEMP_T                   1171
#define IDC_FILEEMP                     1172
#define IDC_FILEMSG                     1173
#define IDC_FILEMSG_T                   1174
#define IDC_WRITEMSG                    1175
#define IDC_DIRMSG                      1176
#define IDC_DIRMSG_T                    1177
#define IDC_CONVERT                     1179
#define IDC_SPLASHW                     1180
#define IDC_SAVEPOS                     1181
#define IDC_SAVEMDI                     1182
#define IDC_MAXIMDI                     1183
#define IDC_SHOWDLG                     1184
#define IDC_TRN_WEBLINK                 1187
#define IDC_GLOBE_ANI                   1188
#define IDC_REGISTRATION                1190
#define IDC_DST_CAPTION                 1191
#define IDC_SC_TEXT                     1192
#define IDC_CV_TEXT                     1193
#define IDC_SUB_TXT                     1194
#define IDC_PPL_TEXT                    1195
#define IDC_SRC_UID_TXT                 1196
#define IDC_DST_UID_TXT                 1197
#define IDC_SRC_PWD_TXT                 1198
#define IDC_DST_PWD_TXT                 1199
#define IDC_DST_OWNER                   1200
#define ID_TRANS_OPTIONS                32770
#define ID_TRANSFER                     32771
#define ID_EXPORT                       32772
#define ID_IMPORT                       32773
#define ID_PROFILE                      32774
#define ID_TOOLBAR_FILE                 32775
#define ID_TOOLBAR_PROFILE              32776
#define ID_DATA_ADD                     32790
#define ID_DATA_RETRIEVE                32791
#define ID_DATA_SAVE                    32792
#define ID_DATA_EDIT                    32793
#define ID_DATA_DELETE                  32794
#define ID_DATA_FIRST                   32795
#define ID_DATA_PREV                    32796
#define ID_DATA_NEXT                    32797
#define ID_DATA_LAST                    32798
#define ID_DATA_CLOSE                   32799
#define ID_START_EXCHANGE               32821
#define ID_STOP_EXCHANGE                32822
#define ID_CUSTOMIZE_TOOLBAR            32829
#define ID_VIEW_PROFILE_TBR             32830
#define ID_CUSTOMIZE_PROFILE_TBR        32831
#define IDS_MS_INIT_TRN                 59394
#define IDS_MS_INIT_PPL                 59395
#define IDS_MS_INIT_PARM                59396
#define IDS_MS_READ_PPL                 59398
#define IDS_MS_CONNECT                  59399
#define IDS_MS_CONN_SRC                 59400
#define IDS_MS_CONN_DST                 59401
#define IDS_MS_READ_SRC_INFO            59402
#define IDS_MS_READ_DST_INFO            59403
#define IDS_MS_FMT_RESULTS              59404
#define IDS_MS_FMT_ROWS                 59406
#define IDS_MS_SUCCESS                  59407
#define IDS_MS_ERRORS                   59408
#define IDS_MS_VIEW_LOG                 59409
#define IDS_MS_PROFILES                 59410
#define IDS_MS_BREAK                    59411
#define IDS_MS_FILTER                   59412
#define IDS_MS_TRN_EDIT                 59413
#define IDS_MS_TRN_NEW                  59414
#define IDS_MS_NEW                      59415
#define IDS_MS_DELETE                   59416
#define IDS_MS_SAVE                     59417
#define IDS_MS_PPL                      59418
#define IDS_MS_PREPARE                  59419
#define IDS_MS_READ_SRC                 59420
#define IDS_MS_READ_DST                 59421
#define IDS_MS_PROCESS_DST              59422
#define IDS_MS_SHOW_MSG                 59423
#define IDS_MS_SEND                     59424
#define IDS_MS_READ_SUBSRC              59425
#define IDS_MS_READ_SUBDST              59426
#define IDS_MS_TABSTART                 59427
#define IDS_MS_TABEND                   59428
#define IDS_MS_SUBSTART                 59429
#define IDS_MS_SUBEND                   59430
#define IDS_MS_FMT_SUBPRC               59431
#define IDS_MS_FMT_SUBDEL               59432
#define IDS_MS_FMT_SUBUPD               59433
#define IDS_MS_FMT_SUBERR               59434
#define IDS_MS_FMT_SUBBCK               59435
#define IDS_MS_FMT_SUBRES               59436
#define IDS_MS_SHOW_ERR                 59437
#define IDS_ER_NOTVALID                 59438
#define IDS_ER_NO_PPL                   59439
#define IDS_ER_NO_EXPR                  59440
#define IDS_ER_NO_TABLE                 59441
#define IDS_ER_NO_KEYS                  59442
#define IDS_ER_NO_FIELDS                59443
#define IDS_ER_NO_MODFLD                59444
#define IDS_ER_NEED_CODE                59445
#define IDS_ER_NEED_NAME                59446
#define IDS_ER_NEED_FILE                59447
#define IDS_ER_NEED_VALUE               59448
#define IDS_ER_NEED_FIELD               59449
#define IDS_ER_NEED_COMMAND             59450
#define IDS_ER_NEED_SQLTAB              59451
#define IDS_ER_NEED_SQLSUB              59452
#define IDS_ER_IGNORE_SQLSUB            59453
#define IDS_ER_DOUBLE_FIELD             59454
#define IDS_ER_DOUBLE_COND              59455
#define IDS_ER_DOUBLE_CODE              59456
#define IDS_ER_FIND_FILE                59457
#define IDS_ER_READ_FILE                59458
#define IDS_ER_OPEN_FILE                59459
#define IDS_ER_WRITE_FILE               59460
#define IDS_ER_CONN_SRC                 59461
#define IDS_ER_CONN_DST                 59462
#define IDS_ER_INSTAB                   59463
#define IDS_ER_UPDTAB                   59464
#define IDS_ER_DELTAB                   59465
#define IDS_ER_INSSUB                   59466
#define IDS_ER_UPDSUB                   59467
#define IDS_ER_DELSUB                   59468
#define IDS_ER_SNTX_PARAM               59469
#define IDS_ER_SNTX_PARAMS              59470
#define IDS_ER_SNTX_MAPTAB              59471
#define IDS_ER_SNTX_MAPSUB              59472
#define IDS_ER_SNTX_CMDTAB              59473
#define IDS_ER_SNTX_CMDSUB              59474
#define IDS_ER_MAIN_TABLE               59475
#define IDS_ER_CRT_SQL                  59476
#define IDS_ER_CRT_TABLE                59477
#define IDS_ER_CRT_INDEX                59478
#define IDS_ER_CRT_TAB                  59479
#define IDS_ER_CRT_SUB                  59480
#define IDS_ER_PREP_SRCTAB              59481
#define IDS_ER_PREP_SRCSUB              59482
#define IDS_ER_PREP_DSTTAB              59483
#define IDS_ER_PREP_DSTSUB              59484
#define IDS_ER_PREP_MSG                 59485
#define IDS_ER_PREP_INSTAB              59486
#define IDS_ER_PREP_UPDTAB              59487
#define IDS_ER_PREP_DELTAB              59488
#define IDS_ER_PREP_INSSUB              59489
#define IDS_ER_PREP_UPDSUB              59490
#define IDS_ER_PREP_DELSUB              59491
#define IDS_ER_PREP_CMDTAB              59492
#define IDS_ER_PREP_CMDSUB              59493
#define IDS_ER_PREP_PARSRCTAB           59494
#define IDS_ER_PREP_SELSRCTAB           59495
#define IDS_ER_PREP_FNDSRCTAB           59496
#define IDS_ER_PREP_PARSRCSUB           59497
#define IDS_ER_PREP_SELSRCSUB           59498
#define IDS_ER_PREP_FNDSRCSUB           59499
#define IDS_ER_PREP_PARDSTTAB           59500
#define IDS_ER_PREP_SELDSTTAB           59501
#define IDS_ER_PREP_FNDDSTTAB           59502
#define IDS_ER_PREP_PARDSTSUB           59503
#define IDS_ER_PREP_SELDSTSUB           59504
#define IDS_ER_PREP_FNDDSTSUB           59505
#define IDS_ER_COUNT_SRCTAB             59506
#define IDS_ER_COUNT_DSTTAB             59507
#define IDS_ER_READ_SRCTAB              59508
#define IDS_ER_READ_DSTTAB              59509
#define IDS_ER_READ_SRCSUB              59510
#define IDS_ER_READ_DSTSUB              59511
#define IDS_ER_FIND_SRCTAB              59512
#define IDS_ER_FIND_DSTTAB              59513
#define IDS_ER_FIND_SRCSUB              59514
#define IDS_ER_FIND_DSTSUB              59515
#define IDS_ER_FIND_PARAM               59516
#define IDS_ER_FIND_CONST               59517
#define IDS_ER_FIND_FLDKEY              59518
#define IDS_ER_FIND_FLDMAP              59519
#define IDS_ER_FIND_FLDSRCTAB           59520
#define IDS_ER_FIND_FLDSRCSUB           59521
#define IDS_ER_FIND_FLDDSTREF           59522
#define IDS_ER_FIND_FLDDSTTAB           59523
#define IDS_ER_FIND_FLDDSTSUB           59524
#define IDS_ER_FIND_FUNC                59525
#define IDS_ER_FIND_PROC                59526
#define IDS_ER_BAD_TYPE                 59527
#define IDS_ER_BAD_DATA                 59528
#define IDS_ER_BAD_CHAR                 59529
#define IDS_ER_BAD_VAL                  59530
#define IDS_ER_BAD_REF                  59531
#define IDS_ER_COMP_DSTTAB              59532
#define IDS_ER_COMP_DSTSUB              59533
#define IDS_ER_CONV_PARTYPE             59534
#define IDS_ER_CONV_FLDTYPE             59535
#define IDS_ER_CONV_PARAM               59536
#define IDS_ER_CONV_CONST               59537
#define IDS_ER_CONV_FIELD               59538
#define IDS_ER_CONV_FUNC                59539
#define IDS_ER_CONV_PROC                59540
#define IDS_ER_DEFINE                   59541
#define IDS_ER_DEF_INDEX                59542
#define IDS_ER_DEF_REFTYPE              59543
#define IDS_ER_DEF_FIELDS               59544
#define IDS_ER_DEF_TABLE                59545
#define IDS_ER_DEF_KEYS                 59546
#define IDS_ER_DEF_REFS                 59547
#define IDS_ER_MOD_FLDKEY               59548
#define IDS_ER_REPL_FLDKEY              59549
#define IDS_ER_REPL_FLDDEF              59550
#define IDS_ER_PARSE_PARAMS             59551
#define IDS_ER_CMD_PARAMS               59552
#define IDS_ER_DESC_FIELDS              59553
#define IDS_ER_DESC_PARAMS              59554
#define IDS_ER_DESC_CATTAB              59555
#define IDS_ER_BIND_PARAM               59556
#define IDS_ER_BIND_FIELD               59557
#define IDS_ER_BIND_PARAMS              59558
#define IDS_ER_BIND_FIELDS              59559
#define IDS_ER_SET_PARAMS               59560
#define IDS_ER_BACK_DETAIL              59561
#define IDS_ER_BACK_CMD                 59562
#define IDS_ER_BACK_OP                  59563
#define IDS_ER_BAD_FLDCMD               59564
#define TAB_FLD_COLNUM                  59565
#define TAB_FLD_COLNAME                 59566
#define TAB_FLD_COLFLAG                 59567
#define TAB_FLD_COLTYPE                 59568
#define TAB_FLD_COLLEN                  59569
#define TAB_FLD_COLDEC                  59570
#define TAB_FLD_COLVAL                  59571
#define TAB_FLD_COMMAND                 59572
#define TAB_FLD_EVENT                   59573
#define TAB_FLD_CODE                    59574
#define TAB_FLD_NAME                    59575
#define TAB_FLD_FILE                    59576
#define IDS_ER_UNS_PARAMS               59577
#define IDS_MS_LOAD_LANG                59578
#define IDS_MS_STOP_PIPE                59579
#define IDS_MS_START_PIPE               59581
#define IDS_MS_RUN_TRN                  59582
#define IDS_MS_START_EXCH               59583
#define IDS_MS_STOP_EXCH                59584
#define IDS_MS_RUN_EXP                  59585
#define IDS_MS_RUN_IMP                  59586
#define IDS_MS_COMPRESS                 59587
#define IDS_MS_EXTRACT                  59588
#define IDS_MS_COPY_FILE                59589
#define IDS_MS_DELETE_FILE              59590
#define IDS_MS_MOVE_FILE                59591
#define IDS_MS_COPY_PROGRESS            59592
#define IDS_MS_COMPRESS_DATA            59593
#define IDS_MS_EXTRACT_DATA             59594
#define IDS_ER_LZW_MAGIC                59595
#define IDS_MS_COMPRESS1                59596
#define IDS_MS_EXTRACT1                 59597
#define IDS_MS_FILE2                    59598
#define IDS_MS_INSERTED                 59599
#define IDS_MS_UPDATED                  59600
#define IDS_MS_DELETED                  59601
#define IDS_MS_ER_STACK_OVF             59602
#define IDS_MS_EXECUTED                 59603
#define IDS_MS_REVERSED                 59604
#define TAB_FLD_TRANS                   59605
#define TAB_FLD_SCHEMA                  59606
#define IDS_SCHEMA_COLUMNS              59607
#define IDS_SCHEMA_COPY                 59608
#define IDS_SCHEMA_COMPLEX              59609
#define IDS_SYS_REG_ROOT                59610
#define IDS_SYS_REG_CONFIG              59611
#define IDS_SYS_REG_CON                 59612
#define IDS_SYS_REG_OPT                 59613
#define IDS_SYS_REG_PIPE                59614
#define IDS_SYS_REG_SET                 59615
#define IDS_SYS_REG_FILE                59616
#define IDS_SYS_REG_INSTFILE            59617
#define IDS_SYS_REG_INSTDATA            59617
#define IDS_SYS_REG_INSTKEY             59618
#define IDS_SYS_REG_INSTVAL             59619
#define IDS_SYS_REG_TRENDKEY            59620
#define IDS_SYS_REG_TRENDVAL            59621
#define IDS_SYS_REG_STENDKEY            59622
#define IDS_SYS_REG_STENDVAL            59623
#define IDS_SYS_REG_COUNTKEY            59624
#define IDS_SYS_REG_COUNTVAL            59625
#define IDS_SYS_REG_DT1STKEY            59626
#define IDS_SYS_REG_DT1STVAL            59627
#define IDS_SYS_REG_DTPREKEY            59628
#define IDS_SYS_REG_DTPREVAL            59629
#define IDS_ER_TRIAL_EXPIRED            59630
#define IDS_ER_INCOR_INSTALL            59631
#define IDS_SYS_TRN_WEBLINK             59632
#define IDS_MS_REGISTRATION             59633
#define IDS_MS_TXT_TRIALVER             59634
#define IDS_ER_TRIAL_COMPLEX            59635
#define IDS_ER_TRIAL_EXCHANGE           59636
#define IDS_ER_WRONG_KEYFILE            59637

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        206
#define _APS_NEXT_COMMAND_VALUE         32832
#define _APS_NEXT_CONTROL_VALUE         1201
#define _APS_NEXT_SYMED_VALUE           107
#endif
#endif
